//! Lets the server's web app — and only the server's origin, in the main
//! window — call the desktop app's own commands.
//!
//! The server address is chosen at run time, so this capability is added at
//! start-up rather than written in `capabilities/`. No plugin command is
//! granted: the web app reaches notifications and the store window only
//! through the app's commands, which check their arguments.

use tauri::ipc::CapabilityBuilder;

use crate::windows::main_window::MAIN_LABEL;

/// The identifier of the capability; one per run, since a changed server
/// address restarts the app.
pub const CAPABILITY_ID: &str = "grocery-server";

/// The permissions (one per command, generated by `build.rs`) the server page
/// gets. `save_server_url` is left out: only the bundled setup page has it.
pub const SERVER_PERMISSIONS: &[&str] = &[
    "allow-desktop-abilities",
    "allow-open-store",
    "allow-fill-store-trolley",
    "allow-open-store-checkout",
    "allow-notify",
];

/// The URL pattern covering every page of `origin`.
pub fn origin_pattern(origin: &str) -> String {
    format!("{}/*", origin.trim_end_matches('/'))
}

/// The capability granting `origin`'s pages in the main window the app's
/// commands.
pub fn server_capability(origin: &str) -> CapabilityBuilder {
    SERVER_PERMISSIONS.iter().fold(
        CapabilityBuilder::new(CAPABILITY_ID)
            .remote(origin_pattern(origin))
            .local(false)
            .window(MAIN_LABEL),
        |capability, permission| capability.permission(*permission),
    )
}

/// Adds the capability for `origin` to the running app.
pub fn grant<R: tauri::Runtime>(app: &tauri::AppHandle<R>, origin: &str) -> tauri::Result<()> {
    use tauri::Manager;
    app.add_capability(server_capability(origin))?;
    log::info!("[server-access] {origin} may call the app's commands");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tauri::ipc::RuntimeCapability;

    #[test]
    fn the_pattern_covers_every_page_of_the_origin() {
        assert_eq!(
            origin_pattern("https://grocery.example.com"),
            "https://grocery.example.com/*"
        );
        assert_eq!(
            origin_pattern("http://10.0.0.2:3000/"),
            "http://10.0.0.2:3000/*"
        );
    }

    #[test]
    fn the_capability_is_remote_main_window_and_never_setup() {
        let tauri::utils::acl::capability::CapabilityFile::Capability(capability) =
            server_capability("https://g.example").build()
        else {
            panic!("one capability expected");
        };
        let built = serde_json::to_value(capability).unwrap();
        assert_eq!(built["identifier"], CAPABILITY_ID);
        assert_eq!(built["local"], false);
        assert_eq!(built["windows"], serde_json::json!([MAIN_LABEL]));
        assert_eq!(
            built["remote"]["urls"],
            serde_json::json!(["https://g.example/*"])
        );
        let permissions = built["permissions"].to_string();
        assert!(permissions.contains("allow-fill-store-trolley"));
        assert!(!permissions.contains("save-server-url"));
    }
}
