//! The spending categories and the words that put a product in each.
//!
//! Order matters only on a tie: the category listed first wins.

/// Every category, each with the words that put a product in it.
pub(super) const CATEGORIES: &[(&str, &[&str])] = &[
    (
        "Fruit & veg",
        &[
            "fruit",
            "vegetable",
            "veg",
            "produce",
            "apple",
            "banana",
            "orange",
            "mandarin",
            "grape",
            "berry",
            "berries",
            "strawberry",
            "blueberry",
            "avocado",
            "lemon",
            "lime",
            "pear",
            "mango",
            "melon",
            "watermelon",
            "kiwi",
            "tomato",
            "potato",
            "onion",
            "garlic",
            "carrot",
            "broccoli",
            "lettuce",
            "spinach",
            "salad",
            "cucumber",
            "capsicum",
            "zucchini",
            "mushroom",
            "pumpkin",
            "cabbage",
            "celery",
            "corn",
            "herb",
        ],
    ),
    (
        "Meat & seafood",
        &[
            "meat", "beef", "steak", "mince", "chicken", "lamb", "pork", "bacon", "ham", "sausage",
            "salami", "turkey", "fish", "salmon", "tuna", "prawn", "seafood", "poultry", "deli",
        ],
    ),
    (
        "Dairy & eggs",
        &[
            "dairy",
            "milk",
            "cheese",
            "yoghurt",
            "yogurt",
            "butter",
            "cream",
            "egg",
            "margarine",
            "custard",
            "tofu",
        ],
    ),
    (
        "Bakery",
        &[
            "bakery",
            "bread",
            "roll",
            "bun",
            "wrap",
            "bagel",
            "croissant",
            "muffin",
            "cake",
            "loaf",
            "crumpet",
            "pita",
            "banana bread",
        ],
    ),
    ("Frozen", &["frozen", "ice cream", "gelato", "ice"]),
    (
        "Drinks",
        &[
            "drink",
            "beverage",
            "water",
            "juice",
            "soft drink",
            "cola",
            "soda",
            "coffee",
            "tea",
            "cordial",
            "kombucha",
            "lemonade",
            "beer",
            "wine",
        ],
    ),
    (
        "Pantry",
        &[
            "pantry",
            "rice",
            "pasta",
            "noodle",
            "flour",
            "sugar",
            "oil",
            "sauce",
            "spice",
            "salt",
            "pepper",
            "cereal",
            "oat",
            "honey",
            "jam",
            "spread",
            "peanut butter",
            "canned",
            "tin",
            "bean",
            "soup",
            "stock",
            "vinegar",
            "baking",
        ],
    ),
    (
        "Snacks & sweets",
        &[
            "snack",
            "chip",
            "crisp",
            "chocolate",
            "milk chocolate",
            "lolly",
            "lollies",
            "biscuit",
            "cracker",
            "nut",
            "popcorn",
            "confectionery",
        ],
    ),
    (
        "Household",
        &[
            "household",
            "toilet paper",
            "toilet tissue",
            "paper towel",
            "tissue",
            "detergent",
            "dishwashing",
            "laundry",
            "cleaning",
            "cleaner",
            "bin bag",
            "garbage bag",
            "foil",
            "cling wrap",
            "sponge",
            "bleach",
        ],
    ),
    (
        "Health & beauty",
        &[
            "health",
            "beauty",
            "personal care",
            "shampoo",
            "conditioner",
            "soap",
            "body wash",
            "toothpaste",
            "toothbrush",
            "deodorant",
            "razor",
            "vitamin",
            "medicine",
            "sunscreen",
        ],
    ),
    ("Baby", &["baby", "nappy", "nappies", "wipes", "formula"]),
    ("Pet", &["pet", "dog", "cat", "kitty litter", "litter"]),
];
