/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as SettingsDeliveryRouteImport } from './routes/settings/delivery'
import { Route as SettingsDislikesRouteImport } from './routes/settings/dislikes'
import { Route as SettingsIntakeRouteImport } from './routes/settings/intake'
import { Route as SettingsItemRulesRouteImport } from './routes/settings/item-rules'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDeliveryRoute = SettingsDeliveryRouteImport.update({
  id: '/settings/delivery',
  path: '/settings/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDislikesRoute = SettingsDislikesRouteImport.update({
  id: '/settings/dislikes',
  path: '/settings/dislikes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntakeRoute = SettingsIntakeRouteImport.update({
  id: '/settings/intake',
  path: '/settings/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsItemRulesRoute = SettingsItemRulesRouteImport.update({
  id: '/settings/item-rules',
  path: '/settings/item-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/logs': typeof LogsRoute
  '/order': typeof OrderRoute
  '/pending': typeof PendingRoute
  '/triage': typeof TriageRoute
  '/settings/delivery': typeof SettingsDeliveryRoute
  '/settings/dislikes': typeof SettingsDislikesRoute
  '/settings/intake': typeof SettingsIntakeRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/logs': typeof LogsRoute
  '/order': typeof OrderRoute
  '/pending': typeof PendingRoute
  '/triage': typeof TriageRoute
  '/settings/delivery': typeof SettingsDeliveryRoute
  '/settings/dislikes': typeof SettingsDislikesRoute
  '/settings/intake': typeof SettingsIntakeRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/logs': typeof LogsRoute
  '/order': typeof OrderRoute
  '/pending': typeof PendingRoute
  '/triage': typeof TriageRoute
  '/settings/delivery': typeof SettingsDeliveryRoute
  '/settings/dislikes': typeof SettingsDislikesRoute
  '/settings/intake': typeof SettingsIntakeRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/logs'
    | '/order'
    | '/pending'
    | '/triage'
    | '/settings/delivery'
    | '/settings/dislikes'
    | '/settings/intake'
    | '/settings/item-rules'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/logs'
    | '/order'
    | '/pending'
    | '/triage'
    | '/settings/delivery'
    | '/settings/dislikes'
    | '/settings/intake'
    | '/settings/item-rules'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/logs'
    | '/order'
    | '/pending'
    | '/triage'
    | '/settings/delivery'
    | '/settings/dislikes'
    | '/settings/intake'
    | '/settings/item-rules'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  LogsRoute: typeof LogsRoute
  OrderRoute: typeof OrderRoute
  PendingRoute: typeof PendingRoute
  TriageRoute: typeof TriageRoute
  SettingsDeliveryRoute: typeof SettingsDeliveryRoute
  SettingsDislikesRoute: typeof SettingsDislikesRoute
  SettingsIntakeRoute: typeof SettingsIntakeRoute
  SettingsItemRulesRoute: typeof SettingsItemRulesRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/delivery': {
      id: '/settings/delivery'
      path: '/settings/delivery'
      fullPath: '/settings/delivery'
      preLoaderRoute: typeof SettingsDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dislikes': {
      id: '/settings/dislikes'
      path: '/settings/dislikes'
      fullPath: '/settings/dislikes'
      preLoaderRoute: typeof SettingsDislikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/intake': {
      id: '/settings/intake'
      path: '/settings/intake'
      fullPath: '/settings/intake'
      preLoaderRoute: typeof SettingsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/item-rules': {
      id: '/settings/item-rules'
      path: '/settings/item-rules'
      fullPath: '/settings/item-rules'
      preLoaderRoute: typeof SettingsItemRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  LogsRoute: LogsRoute,
  OrderRoute: OrderRoute,
  PendingRoute: PendingRoute,
  TriageRoute: TriageRoute,
  SettingsDeliveryRoute: SettingsDeliveryRoute,
  SettingsDislikesRoute: SettingsDislikesRoute,
  SettingsIntakeRoute: SettingsIntakeRoute,
  SettingsItemRulesRoute: SettingsItemRulesRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
