/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as SettingsItemRulesRouteImport } from './routes/settings/item-rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsItemRulesRoute = SettingsItemRulesRouteImport.update({
  id: '/settings/item-rules',
  path: '/settings/item-rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pending': typeof PendingRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pending': typeof PendingRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pending': typeof PendingRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pending' | '/settings/item-rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pending' | '/settings/item-rules'
  id: '__root__' | '/' | '/pending' | '/settings/item-rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PendingRoute: typeof PendingRoute
  SettingsItemRulesRoute: typeof SettingsItemRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/item-rules': {
      id: '/settings/item-rules'
      path: '/settings/item-rules'
      fullPath: '/settings/item-rules'
      preLoaderRoute: typeof SettingsItemRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PendingRoute: PendingRoute,
  SettingsItemRulesRoute: SettingsItemRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
