/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as SettingsIntakeRouteImport } from './routes/settings/intake'
import { Route as SettingsItemRulesRouteImport } from './routes/settings/item-rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntakeRoute = SettingsIntakeRouteImport.update({
  id: '/settings/intake',
  path: '/settings/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsItemRulesRoute = SettingsItemRulesRouteImport.update({
  id: '/settings/item-rules',
  path: '/settings/item-rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/order': typeof OrderRoute
  '/pending': typeof PendingRoute
  '/triage': typeof TriageRoute
  '/settings/intake': typeof SettingsIntakeRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/order': typeof OrderRoute
  '/pending': typeof PendingRoute
  '/triage': typeof TriageRoute
  '/settings/intake': typeof SettingsIntakeRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/order': typeof OrderRoute
  '/pending': typeof PendingRoute
  '/triage': typeof TriageRoute
  '/settings/intake': typeof SettingsIntakeRoute
  '/settings/item-rules': typeof SettingsItemRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/order'
    | '/pending'
    | '/triage'
    | '/settings/intake'
    | '/settings/item-rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/order'
    | '/pending'
    | '/triage'
    | '/settings/intake'
    | '/settings/item-rules'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/order'
    | '/pending'
    | '/triage'
    | '/settings/intake'
    | '/settings/item-rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  OrderRoute: typeof OrderRoute
  PendingRoute: typeof PendingRoute
  TriageRoute: typeof TriageRoute
  SettingsIntakeRoute: typeof SettingsIntakeRoute
  SettingsItemRulesRoute: typeof SettingsItemRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/intake': {
      id: '/settings/intake'
      path: '/settings/intake'
      fullPath: '/settings/intake'
      preLoaderRoute: typeof SettingsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/item-rules': {
      id: '/settings/item-rules'
      path: '/settings/item-rules'
      fullPath: '/settings/item-rules'
      preLoaderRoute: typeof SettingsItemRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  OrderRoute: OrderRoute,
  PendingRoute: PendingRoute,
  TriageRoute: TriageRoute,
  SettingsIntakeRoute: SettingsIntakeRoute,
  SettingsItemRulesRoute: SettingsItemRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
